import { User, Account, Transaction, Card, Language, Goal, CashbackCategory } from './types';

export const CURRENT_USER: User = {
  id: 'u1',
  name: 'RHODIN Sofia Ann-Charlotte',
  email: 'sofia.rhodin@ecobank.com',
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80'
};

export const ACCOUNTS: Account[] = [
  {
    id: 'a1',
    type: 'Compte Courant',
    balance: 195000000, // Updated to 195,000,000 XOF
    currency: 'XOF',
    accountNumber: 'FR76 3000 4000 5000'
  }
];

// Added initial deposit transaction starting 2nd week of 2026
export const RECENT_TRANSACTIONS: Transaction[] = [
    {
        id: 't1',
        date: '2026-01-08T09:30:00Z', // Thursday, Jan 8th 2026
        recipient: 'Dépôt Initial',
        amount: 195000000, // Updated to 195,000,000 XOF
        currency: 'XOF',
        type: 'credit',
        category: 'Virement Entrant',
        logo: 'https://i.imgur.com/eAwClBc.png'
    }
];

export const GOALS: Goal[] = [];

export const CARDS: Card[] = [
    {
        id: 'c1',
        type: 'Visa',
        number: '4970 1102 3044 5509',
        expiry: '12/28',
        holder: 'RHODIN Sofia',
        status: 'active',
        balance: 195000000,
        currency: 'XOF'
    }
];

export const CASHBACK_DATA: CashbackCategory[] = [
    { 
      id: '1', 
      name: 'Carrefour', 
      rate: 2.5, 
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Carrefour_logo.svg/2048px-Carrefour_logo.svg.png', 
      category: 'Shopping' 
    },
    { 
      id: '2', 
      name: 'Total Energies', 
      rate: 1.5, 
      logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/9/9b/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png', 
      category: 'Transport' 
    },
    { 
      id: '3', 
      name: 'Auchan', 
      rate: 3.0, 
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Auchan_Logo_2015.svg/1200px-Auchan_Logo_2015.svg.png', 
      category: 'Shopping' 
    }
];

export const TRANSLATIONS = {
  [Language.EN]: {
    dashboard: 'Dashboard',
    wallet: 'Wallet',
    payments: 'Transfers',
    statistics: 'Statistics',
    cashback: 'Cashback',
    support: 'Support',
    settings: 'Settings',
    logout: 'Logout',
    welcome: 'Welcome',
    monthlyExpenses: 'Monthly Expenses',
    monthlyIncome: 'Monthly Income',
    expenseDesc: 'Spending is consistent',
    incomeDesc: 'Income received',
    viewMore: 'View More',
    incomeLabel: 'Income',
    timeRange: 'Time Range',
    cards: 'My Cards',
    noCashback: 'No Cashback Yet',
    noCashbackDesc: 'Start spending to earn cashback',
    transactions: 'Transactions',
    noTransactions: 'No recent transactions',
    noTransactionsDesc: 'Your transactions will appear here',
    goals: 'Savings Goals',
    noGoals: 'No active goals',
    noGoalsDesc: 'Create a goal to start saving',
    addGoal: 'Add Goal',
    step1Title: 'Select Account',
    step2Title: 'Beneficiary Details',
    step3Title: 'Confirmation',
    selectAccountDesc: 'Choose the source account',
    recipient: 'Recipient',
    summary: 'Summary',
    transferSuccess: 'Transfer Initiated',
    transferSentDesc: 'Your transfer has been successfully processed.',
    gotIt: 'Got it',
    makeAnother: 'Make another',
    transferSummary: 'Transfer Summary',
    transferReason: 'Reference',
    dateLabel: 'Date',
    accountLabel: 'Account',
    iban: 'IBAN',
    amount: 'Amount',
    fees: 'Fees',
    totalDebited: 'Total Debited',
    beneficiaryName: 'Last Name',
    beneficiaryFirstName: 'First Name',
    bankName: 'Bank Name',
    from: 'From',
    to: 'To',
    back: 'Back',
    next: 'Next',
    confirmTransfer: 'Confirm Transfer',
    myCards: 'My Cards',
    active: 'Active',
    frozen: 'Frozen',
    freeze: 'Freeze Card',
    addMoney: 'Add Money',
    totalAssets: 'Total Assets',
    spendingLimit: 'Monthly Limit',
    assetEvolution: 'Asset Evolution',
    myAccounts: 'My Accounts',
    netSavings: 'Net Savings',
    incomeVsExpense: 'Income vs Expense',
    spendingCategories: 'Spending by Category',
    others: 'Others',
    totalEarned: 'Total Earned',
    pending: 'Pending',
    noPending: 'No pending cashback',
    availableOffers: 'Available Offers',
    activate: 'Activate',
    cashbackHistory: 'Cashback History',
    noHistory: 'No cashback history available',
    startEarning: 'Start shopping to earn cashback!',
    currentLangName: 'English',
    login: 'Login',
    userId: 'User ID',
    password: 'Password',
    continue: 'Continue',
    forgotPassword: 'Forgot Password?',
    privacy: 'Privacy Policy',
    security: 'Security',
    agreement: 'User Agreement',
    rights: 'All rights reserved.',
    supportCenter: 'Support Center',
    howCanWeHelp: 'How can we help you today?',
    search: 'Search for help...',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    faq: 'Frequently Asked Questions',
    faq1: 'How do I reset my password?',
    faq1Desc: 'Go to Settings > Security > Change Password.',
    faq2: 'What are the transfer limits?',
    faq2Desc: 'Daily limit is 2,000,000 XOF.',
    faq3: 'How to block my card?',
    faq3Desc: 'Go to Cards > Select Card > Freeze.',
    generalSettings: 'General',
    notifications: 'Notifications',
    emailNotif: 'Email Notifications',
    pushNotif: 'Push Notifications',
    securitySettings: 'Security',
    changePassword: 'Change Password',
    enable2FA: 'Enable 2FA',
    saveChanges: 'Save Changes'
  },
  [Language.FR]: {
    dashboard: 'Accueil',
    wallet: 'Portefeuille',
    payments: 'Virements',
    statistics: 'Statistiques',
    cashback: 'Cashback',
    support: 'Aide',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    welcome: 'Bonjour',
    monthlyExpenses: 'Dépenses du mois',
    monthlyIncome: 'Revenus du mois',
    expenseDesc: 'Dépenses stables',
    incomeDesc: 'Revenus reçus',
    viewMore: 'Voir plus',
    incomeLabel: 'Revenus',
    timeRange: 'Période',
    cards: 'Mes Cartes',
    noCashback: 'Aucun cashback',
    noCashbackDesc: 'Utilisez votre carte pour gagner du cashback',
    transactions: 'Transactions',
    noTransactions: 'Aucune transaction récente',
    noTransactionsDesc: 'Vos transactions apparaîtront ici',
    goals: 'Objectifs',
    noGoals: 'Aucun objectif',
    noGoalsDesc: 'Créez un objectif pour épargner',
    addGoal: 'Nouvel objectif',
    step1Title: 'Sélection du compte',
    step2Title: 'Bénéficiaire',
    step3Title: 'Confirmation',
    selectAccountDesc: 'Choisissez le compte source',
    recipient: 'Bénéficiaire',
    summary: 'Récapitulatif',
    transferSuccess: 'Virement initié',
    transferSentDesc: 'Votre virement a été traité avec succès.',
    gotIt: 'Compris',
    makeAnother: 'Nouveau virement',
    transferSummary: 'Détails du virement',
    transferReason: 'Motif',
    dateLabel: 'Date',
    accountLabel: 'Compte',
    iban: 'IBAN',
    amount: 'Montant',
    fees: 'Frais',
    totalDebited: 'Total débité',
    beneficiaryName: 'Nom',
    beneficiaryFirstName: 'Prénom',
    bankName: 'Banque',
    from: 'De',
    to: 'Vers',
    back: 'Retour',
    next: 'Suivant',
    confirmTransfer: 'Confirmer',
    myCards: 'Mes Cartes',
    active: 'Active',
    frozen: 'Bloquée',
    freeze: 'Bloquer la carte',
    addMoney: 'Ajouter de l\'argent',
    totalAssets: 'Total des avoirs',
    spendingLimit: 'Plafond mensuel',
    assetEvolution: 'Évolution des avoirs',
    myAccounts: 'Mes Comptes',
    netSavings: 'Épargne nette',
    incomeVsExpense: 'Revenus vs Dépenses',
    spendingCategories: 'Dépenses par catégorie',
    others: 'Autres',
    totalEarned: 'Total gagné',
    pending: 'En attente',
    noPending: 'Aucun cashback en attente',
    availableOffers: 'Offres disponibles',
    activate: 'Activer',
    cashbackHistory: 'Historique Cashback',
    noHistory: 'Aucun historique',
    startEarning: 'Commencez vos achats pour gagner !',
    currentLangName: 'Français',
    login: 'Connexion',
    userId: 'Identifiant',
    password: 'Mot de passe',
    continue: 'Continuer',
    forgotPassword: 'Mot de passe oublié ?',
    privacy: 'Politique de confidentialité',
    security: 'Sécurité',
    agreement: 'Conditions d\'utilisation',
    rights: 'Tous droits réservés.',
    supportCenter: 'Centre d\'aide',
    howCanWeHelp: 'Comment pouvons-nous vous aider ?',
    search: 'Rechercher de l\'aide...',
    callUs: 'Appelez-nous',
    emailUs: 'Écrivez-nous',
    faq: 'Questions fréquentes',
    faq1: 'Comment changer mon mot de passe ?',
    faq1Desc: 'Allez dans Paramètres > Sécurité > Changer mot de passe.',
    faq2: 'Quelles sont les limites de virement ?',
    faq2Desc: 'La limite quotidienne est de 2 000 000 XOF.',
    faq3: 'Comment bloquer ma carte ?',
    faq3Desc: 'Allez dans Cartes > Sélectionner carte > Bloquer.',
    generalSettings: 'Général',
    notifications: 'Notifications',
    emailNotif: 'Notifications par email',
    pushNotif: 'Notifications push',
    securitySettings: 'Sécurité',
    changePassword: 'Changer le mot de passe',
    enable2FA: 'Activer la 2FA',
    saveChanges: 'Enregistrer'
  }
};