import { User, Account, Transaction, Card, Language, Goal, CashbackCategory } from './types';

export const CURRENT_USER: User = {
  id: 'u1',
  name: 'ROHDIN Sofia Ann-Charlotte',
  email: 'rohdinlotta@gmail.com',
  avatar: 'https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y'
};

// Le solde initial est de 195 000 000. 
// On affiche le solde APPRÈS le retrait de 32 809,42.
export const ACCOUNTS: Account[] = [
  {
    id: 'a1',
    type: 'Compte Courant',
    balance: 194967190.58,
    currency: 'XOF',
    accountNumber: 'CI201 01001 111238311499 32'
  }
];

export const RECENT_TRANSACTIONS: Transaction[] = [
    {
        id: 't-success-atm',
        date: '2026-01-25T12:24:00Z',
        recipient: 'BANKOMAT ICA GAVLE SE',
        amount: 32809.42,
        currency: 'XOF',
        type: 'debit',
        category: 'Retrait ATM',
        status: 'completed',
        logo: 'https://cdn-icons-png.flaticon.com/512/3013/3013210.png'
    },
    {
        id: 't1',
        date: '2026-01-08T09:30:00Z',
        recipient: 'Dépôt Initial',
        amount: 195000000,
        currency: 'XOF',
        type: 'credit',
        category: 'Virement Entrant',
        logo: 'https://i.imgur.com/eAwClBc.png'
    }
];

export const GOALS: Goal[] = [];

export const CARDS: Card[] = [
    {
        id: 'c1',
        type: 'Visa',
        number: '4305 0122 2240 4286',
        expiry: '03/28',
        holder: 'ROHDIN Sofia Ann-Charlotte',
        status: 'active',
        balance: 194967190.58,
        currency: 'XOF'
    }
];

export const CASHBACK_DATA: CashbackCategory[] = [
    { 
      id: '1', 
      name: 'Carrefour', 
      rate: 2.5, 
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Carrefour_logo.svg/2048px-Carrefour_logo.svg.png', 
      category: 'Shopping' 
    },
    { 
      id: '2', 
      name: 'Total Energies', 
      rate: 1.5, 
      logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/9/9b/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png', 
      category: 'Transport' 
    },
    { 
      id: '3', 
      name: 'Auchan', 
      rate: 3.0, 
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Auchan_Logo_2015.svg/1200px-Auchan_Logo_2015.svg.png', 
      category: 'Shopping' 
    }
];

export const TRANSLATIONS: any = {
  [Language.FR]: {
    dashboard: 'Tableau de bord',
    wallet: 'Portefeuille',
    payments: 'Virements',
    statistics: 'Statistiques',
    cashback: 'Cashback',
    support: 'Aide',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    welcome: 'Bonjour',
    monthlyExpenses: 'Dépenses du mois',
    monthlyIncome: 'Revenus du mois',
    expenseDesc: 'Dépenses stables',
    incomeDesc: 'Revenus reçus',
    viewMore: 'Voir plus',
    incomeLabel: 'Revenus',
    timeRange: 'Période',
    cards: 'Mes Cartes',
    noCashback: 'Pas de Cashback',
    noCashbackDesc: 'Utilisez votre carte pour gagner du cashback',
    transactions: 'Transactions',
    noTransactions: 'Aucune transaction récente',
    noTransactionsDesc: 'Vos transactions apparaîtront ici',
    goals: 'Objectifs d\'épargne',
    noGoals: 'Aucun objectif',
    noGoalsDesc: 'Créez un objectif pour épargner',
    addGoal: 'Nouvel Objectif',
    step1Title: 'Sélectionner Compte',
    step2Title: 'Bénéficiaire',
    step3Title: 'Confirmation',
    selectAccountDesc: 'Choisir le compte source',
    recipient: 'Bénéficiaire',
    summary: 'Résumé',
    transferSuccess: 'Virement Initié',
    transferSentDesc: 'Votre virement a été traité avec succès.',
    gotIt: 'Compris',
    makeAnother: 'Faire un autre',
    transferSummary: 'Résumé du virement',
    transferReason: 'Motif',
    dateLabel: 'Date',
    accountLabel: 'Compte',
    iban: 'IBAN',
    amount: 'Montant',
    fees: 'Frais',
    totalDebited: 'Total Débité',
    beneficiaryName: 'Nom',
    beneficiaryFirstName: 'Prénom',
    bankName: 'Banque',
    from: 'De',
    to: 'Vers',
    back: 'Retour',
    next: 'Suivant',
    confirmTransfer: 'Confirmer',
    myCards: 'Mes Cartes',
    active: 'Active',
    frozen: 'Bloquée',
    freeze: 'Bloquer la carte',
    addMoney: 'Recharger',
    totalAssets: 'Total Avoirs',
    spendingLimit: 'Plafond Mensuel',
    assetEvolution: 'Évolution des avoirs',
    myAccounts: 'Mes Comptes',
    netSavings: 'Épargne Nette',
    incomeVsExpense: 'Revenus vs Dépenses',
    spendingCategories: 'Dépenses par catégorie',
    others: 'Autres',
    totalEarned: 'Total Gagné',
    pending: 'En attente',
    noPending: 'Aucun cashback en attente',
    availableOffers: 'Offres Disponibles',
    activate: 'Activer',
    cashbackHistory: 'Historique Cashback',
    noHistory: 'Aucun historique',
    startEarning: 'Faites des achats pour gagner du cashback !',
    currentLangName: 'Français',
    login: 'Connexion',
    userId: 'Identifiant',
    password: 'Mot de passe',
    continue: 'Continuer',
    forgotPassword: 'Mot de passe oublié ?',
    privacy: 'Politique de confidentialité',
    security: 'Sécurité',
    agreement: 'Conditions d\'utilisation',
    rights: 'Tous droits réservés.',
    supportCenter: 'Centre d\'aide',
    howCanWeHelp: 'Comment pouvons-nous vous aider ?',
    search: 'Rechercher de l\'aide...',
    callUs: 'Appelez-nous',
    emailUs: 'Envoyez un email',
    faq: 'Foire Aux Questions',
    faq1: 'Comment réinitialiser mon mot de passe ?',
    faq1Desc: 'Pour réinitialiser votre mot de passe, allez dans Paramètres > Sécurité > Changer le mot de passe. Si vous ne pouvez pas vous connecter, utilisez le lien "Mot de passe oublié" sur l\'écran de connexion.',
    faq2: 'Quelles sont les limites de virement ?',
    faq2Desc: 'La limite standard quotidienne est de 2 000 000 XOF. La limite hebdomadaire est de 10 000 000 XOF.',
    faq3: 'Comment bloquer ma carte ?',
    faq3Desc: 'Vous pouvez bloquer votre carte instantanément depuis le Tableau de bord ou l\'onglet Cartes.',
    faq4: 'Comment télécharger mon RIB ?',
    faq4Desc: 'Allez dans l\'onglet Portefeuille, cliquez sur le menu du compte et choisissez "Télécharger RIB".',
    faq5: 'Quels sont les frais de virement ?',
    faq5Desc: 'Les virements internes Ecobank sont gratuits. Les virements UEMOA coûtent 500 XOF.',
    generalSettings: 'Général',
    notifications: 'Notifications',
    emailNotif: 'Notifications Email',
    pushNotif: 'Notifications Push',
    securitySettings: 'Sécurité',
    changePassword: 'Changer le mot de passe',
    enable2FA: 'Activer 2FA',
    saveChanges: 'Enregistrer',
    createGoal: 'Créer un objectif',
    goalName: 'Nom de l\'objectif',
    targetAmount: 'Montant cible',
    cancel: 'Annuler',
    create: 'Créer',
    downloadPdf: 'Télécharger PDF',
    filter: 'Filtrer',
    manageGoals: 'Gérer les objectifs',
    archivedGoals: 'Objectifs archivés',
    cardHolder: 'Titulaire',
    expires: 'Expire',
    showCardDetails: 'Voir détails',
    hideCardDetails: 'Masquer détails',
    unfreeze: 'Débloquer la carte',
    month1: '1 Mois',
    month3: '3 Mois',
    month6: '6 Mois',
    notificationsTitle: 'Notifications',
    noNotifications: 'Aucune notification',
    thisMonth: 'ce mois-ci',
    greatJobSaving: "Excellent travail de gestion ce mois-ci.",
    downloadStatement: 'Télécharger relevé',
    downloadIBAN: 'Télécharger RIB',
    openSavings: 'Ouvrir Épargne',
    startSaving: 'Commencer à épargner',
    vsLastMonth: 'vs mois dernier',
    noExpensesYet: 'Aucune dépense',
    ofIncome: 'des revenus',
    premiumCustomer: 'Client Premium depuis 2024',
    personalInfo: 'Informations personnelles',
    accountDetails: 'Détails du compte',
    editPhoto: 'Modifier Photo',
    appLanguage: 'Langue de l\'application',
    receiveSummary: 'Recevoir résumés hebdo',
    transactionAlerts: 'Alertes de transaction',
    lastChanged: 'Modifié il y a 3 mois',
    update: 'Mettre à jour',
    secureAccount: 'Sécuriser votre compte',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer mot de passe',
    savePassword: 'Enregistrer mot de passe',
    showPin: 'Voir le code PIN',
    hidePin: 'Masquer le PIN',
    pinDesc: "Afficher votre code à 4 chiffres",
    cardSettings: 'Paramètres de la carte',
    tempDisable: 'Désactiver temporairement votre carte',
    addNewCard: 'Nouvelle Carte',
    jan: 'Jan',
    feb: 'Fév',
    mar: 'Mar',
    apr: 'Avr',
    may: 'Mai',
    jun: 'Juin',
    jul: 'Juil',
    aug: 'Août',
    sep: 'Sep',
    oct: 'Oct',
    nov: 'Nov',
    dec: 'Déc'
  },
  [Language.EN]: {
    dashboard: 'Dashboard',
    wallet: 'Wallet',
    payments: 'Transfers',
    statistics: 'Statistics',
    cashback: 'Cashback',
    support: 'Support',
    settings: 'Settings',
    logout: 'Logout',
    welcome: 'Welcome',
    monthlyExpenses: 'Monthly Expenses',
    monthlyIncome: 'Monthly Income',
    expenseDesc: 'Spending is consistent',
    incomeDesc: 'Income received',
    viewMore: 'View More',
    incomeLabel: 'Income',
    timeRange: 'Time Range',
    cards: 'My Cards',
    noCashback: 'No Cashback Yet',
    noCashbackDesc: 'Start spending to earn cashback',
    transactions: 'Transactions',
    noTransactions: 'No recent transactions',
    noTransactionsDesc: 'Your transactions will appear here',
    goals: 'Savings Goals',
    noGoals: 'No active goals',
    noGoalsDesc: 'Create a goal to start saving',
    addGoal: 'Add Goal',
    step1Title: 'Select Account',
    step2Title: 'Beneficiary Details',
    step3Title: 'Confirmation',
    selectAccountDesc: 'Choose the source account',
    recipient: 'Recipient',
    summary: 'Summary',
    transferSuccess: 'Transfer Initiated',
    transferSentDesc: 'Your transfer has been successfully processed.',
    gotIt: 'Got it',
    makeAnother: 'Make another',
    transferSummary: 'Transfer Summary',
    transferReason: 'Reference',
    dateLabel: 'Date',
    accountLabel: 'Account',
    iban: 'IBAN',
    amount: 'Amount',
    fees: 'Fees',
    totalDebited: 'Total Debited',
    beneficiaryName: 'Last Name',
    beneficiaryFirstName: 'First Name',
    bankName: 'Bank Name',
    from: 'From',
    to: 'To',
    back: 'Back',
    next: 'Next',
    confirmTransfer: 'Confirm Transfer',
    myCards: 'My Cards',
    active: 'Active',
    frozen: 'Frozen',
    freeze: 'Freeze Card',
    addMoney: 'Add Money',
    totalAssets: 'Total Assets',
    spendingLimit: 'Monthly Limit',
    assetEvolution: 'Asset Evolution',
    myAccounts: 'My Accounts',
    netSavings: 'Net Savings',
    incomeVsExpense: 'Income vs Expense',
    spendingCategories: 'Spending by Category',
    others: 'Others',
    totalEarned: 'Total Earned',
    pending: 'Pending',
    noPending: 'No pending cashback',
    availableOffers: 'Available Offers',
    activate: 'Activate',
    cashbackHistory: 'Cashback History',
    noHistory: 'No cashback history available',
    startEarning: 'Start shopping to earn cashback!',
    currentLangName: 'English',
    login: 'Login',
    userId: 'User ID',
    password: 'Password',
    continue: 'Continue',
    forgotPassword: 'Forgot Password?',
    privacy: 'Privacy Policy',
    security: 'Security',
    agreement: 'User Agreement',
    rights: 'All rights reserved.',
    supportCenter: 'Support Center',
    howCanWeHelp: 'How can we help you today?',
    search: 'Search for help...',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    faq: 'Frequently Asked Questions',
    faq1: 'How do I reset my online banking password?',
    faq1Desc: 'To reset your password, navigate to the Settings tab and select "Security". Click on "Change Password" and follow the instructions.',
    faq2: 'What are the daily and weekly transfer limits?',
    faq2Desc: 'For security reasons, the standard daily transfer limit is set to 2,000,000 XOF. The weekly cumulative limit is 10,000,000 XOF.',
    faq3: 'How do I block or unblock my card?',
    faq3Desc: 'You can instantly freeze your card directly from the Dashboard by clicking the three dots above your card and selecting "Freeze Card".',
    faq4: 'How can I download my account statement or IBAN?',
    faq4Desc: 'You can download official account statements (PDF/Excel) and your IBAN details directly from the "Wallet" tab.',
    faq5: 'What are the fees for interbank transfers?',
    faq5Desc: 'Internal Ecobank transfers are free. WAEMU transfers cost 500 XOF.',
    generalSettings: 'General',
    notifications: 'Notifications',
    emailNotif: 'Email Notifications',
    pushNotif: 'Push Notifications',
    securitySettings: 'Security',
    changePassword: 'Change Password',
    enable2FA: 'Enable 2FA',
    saveChanges: 'Save Changes',
    createGoal: 'Create Savings Goal',
    goalName: 'Goal Name',
    targetAmount: 'Target Amount',
    cancel: 'Cancel',
    create: 'Create',
    downloadPdf: 'Download PDF',
    filter: 'Filter',
    manageGoals: 'Manage Goals',
    archivedGoals: 'Archived Goals',
    cardHolder: 'Card Holder',
    expires: 'Expires',
    showCardDetails: 'Show Details',
    hideCardDetails: 'Hide Details',
    unfreeze: 'Unfreeze Card',
    month1: '1 Month',
    month3: '3 Months',
    month6: '6 Months',
    notificationsTitle: 'Notifications',
    noNotifications: 'No notifications',
    thisMonth: 'this month',
    greatJobSaving: "Excellent management job this month.",
    downloadStatement: 'Download Statement',
    downloadIBAN: 'Download IBAN',
    openSavings: 'Open Savings',
    startSaving: 'Start saving',
    vsLastMonth: 'vs last month',
    noExpensesYet: 'No expenses',
    ofIncome: 'of income',
    premiumCustomer: 'Premium Client since 2024',
    personalInfo: 'Personal Information',
    accountDetails: 'Account Details',
    editPhoto: 'Edit Photo',
    appLanguage: 'App Language',
    receiveSummary: 'Receive weekly summaries',
    transactionAlerts: 'Transaction alerts',
    lastChanged: 'Changed 3 months ago',
    update: 'Update',
    secureAccount: 'Secure your account',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    savePassword: 'Save password',
    showPin: 'Show PIN code',
    hidePin: 'Hide PIN',
    pinDesc: "Show your 4-digit code",
    cardSettings: 'Card Settings',
    tempDisable: 'Temporarily disable your card',
    addNewCard: 'New Card',
    jan: 'Jan',
    feb: 'Feb',
    mar: 'Mar',
    apr: 'Apr',
    may: 'May',
    jun: 'Jun',
    jul: 'Jul',
    aug: 'Aug',
    sep: 'Sep',
    oct: 'Oct',
    nov: 'Nov',
    dec: 'Dec'
  }
};